### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Taknax** [Lomeli12/TrophySlots#29]
I like the idea behind TrophySlots, but in my modpack are much advancements, which are gained by joining. In my case much slots are open initialy. I would like a mode (maybe configurable via configs), where i can set experience to open the slolts, instead of advancements.

**Comment by Lomeli12** [comment]
You can disable slots unlocked via achievements and instead reward the player the trophy item to unlock slots for them.

```toml
[general]
	#Allows you to unlock slots by completing advancements.
	unlockViaAdvancements = false
        #Allows you to unlock slots using trophies.
	canUseTrophy = true
```
